// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "providers": string;
      "activeProviderId": string;
      "targetLang": string;
      "shortcut": string;
      "streaming": boolean;
      "temperature": number;
      "topP": string;
      "topK": string;
      "repetitionPenalty": string;
      "maxOutputTokens": string;
      "cachePersist": boolean;
      "cacheLimit": number;
      "cachePersistLimit": number;
    };
  }
}
